version: '3.9'
services:
  srv:
    # container_name: srv
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.development
    networks:
      - app_network
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - /app/node_modules
    command: npm run start:dev 

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    networks:
      - app_network
    ports:
      - 5000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    container_name: redis
    image: redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
